services:

    neo_main.neo_service:
        class: Neo\MainBundle\Services\NeoService
        arguments: [@doctrine.orm.entity_manager]

    neo_main.parameters_conversion_service:
        class: Neo\MainBundle\Services\ParametersConversionService
